### PR TITLE
Update FundAllocation.sol

### PR DESCRIPTION
**Pull request by PranavLakkadi13**
use mapping to keep track of the voters instead of a array

### CODE REVIEW

**Comment by Sumer312** [comment]
Oh makes sense because of constant look up time. But dude don't remove the new keyword, it throws a bunch of errors.

**Comment by PranavLakkadi13** [comment]
it's working for me and I have tested it as well and it's the right way to do it

**Comment by Sumer312** [comment]
Show me the test files

**Comment by PranavLakkadi13** [comment]
go through my voting dapp repo and look it up in test folder

**Comment by Sumer312** [comment]
Error: Transaction reverted: function returned an unexpected amount of data
      at FundAllocation.onlyMembers (contracts/FundAllocation.sol:37)
      at FundAllocation.activateProposal (contracts/FundAllocation.sol:138)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async EthModule._estimateGasAction (/home/sumer/Documents/solidity/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:439:7)
      at async HardhatNetworkProvider._sendWithLogging (/home/sumer/Documents/solidity/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:145:22)
      at async HardhatNetworkProvider.request (/home/sumer/Documents/solidity/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:122:18)
      at async JsonRpcHandler._handleRequest (/home/sumer/Documents/solidity/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:191:20)
      at async JsonRpcHandler._handleSingleRequest (/home/sumer/Documents/solidity/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:152:17)
      at async Server.JsonRpcHandler.handleHttp (/home/sumer/Documents/solidity/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)
      
This is the error I'm getting when I remove the new keyword, if add it then ik it won't work because a new instance of a Soulbound Token instantiated and that instance is not minted by anyone, have to find some other way.

**Comment by PranavLakkadi13** [comment]
u are getting that error bcoz u are passing the eoa address instead of the token contract address try to pass the token address u issue might be solved and remove new keyword

**Comment by Sumer312** [comment]
Damn I completely forgot about that, it worked thanks.

**Comment by Sumer312** [comment]
But why did you remove other lines where is set all the boolean variables.

**Comment by PranavLakkadi13** [comment]
> But why did you remove other lines where is set all the boolean variables.

I removed the other variables bcoz u r initiating them to their default values, so u might as well not do it and remove the require statement from create proposal statement and keep the way i created the pr for

**Comment by Sumer312** [comment]
Oh thanks.

**Pull request merged**
